add_newline = false

[character]
success_symbol = "[➜](bold green)"
error_symbol = "[x](bold red)"

[directory]
truncation_length = 5

[git_branch]
symbol = " "
format = "[$symbol$branch]($style) "

[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'
ahead = "⇡${count}"
behind = "⇣${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
modified = "!${count}"
untracked = "?${count}"
staged = "+${count}"
deleted = "✘${count}"

[golang]
symbol = " "
format = "[$symbol($version)]($style) "

[python]
symbol = " "
format = '[$symbol($version)(\($virtualenv\))]($style) '

[nodejs]
symbol = " "
format = "[$symbol($version)]($style) "

[cmd_duration]
min_time = 2_000
format = "[ $duration]($style) "
